with Ada.Text_IO;
with Ada.Strings.Fixed;
with Ada.Integer_Text_IO;
with Interfaces;

package body Home_Pictures.BMP.Puts is

   procedure Put_Lines (Surface : BMP_Information) is
      use Ada.Text_IO;
      use Ada.Integer_Text_IO;
      use Ada.Strings.Fixed;
      use Interfaces;
      package Unsigned_32_Text_IO is new Modular_IO (Unsigned_32);
      package Unsigned_16_Text_IO is new Modular_IO (Unsigned_16);
      use Unsigned_32_Text_IO;
      use Unsigned_16_Text_IO;
      Column_1_Width : constant := 25;
      Column_2_Width : constant := 20;
   begin
      Put (Head ("BMP_Information_Header'Size / Storage_Unit", Column_1_Width));
      Put (Integer (BMP_Information_Header'Size / Storage_Unit), Column_2_Width);
      New_Line;


      Put (Head ("Signature", Column_1_Width));
      Put (Tail (Surface.File.Sign'Img, Column_2_Width));
      New_Line;
      Put (Head("Size ", Column_1_Width));
      Put (Surface.File.Size, Column_2_Width);
      New_Line;
      Put (Head("Reserved_1", Column_1_Width));
      Put (Surface.File.Reserved_1, Column_2_Width);
      New_Line;
      Put (Head("Reserved_1", Column_1_Width));
      Put (Surface.File.Reserved_1, Column_2_Width);
      New_Line;
      Put (Head("Offset", Column_1_Width));
      Put (Surface.File.Offset, Column_2_Width);
      New_Line;
      Put (Head("Header_Size", Column_1_Width));
      Put (Surface.Information.Header_Size, Column_2_Width);
      New_Line;
      Put (Head("Width", Column_1_Width));
      Put (Surface.Information.Width, Column_2_Width);
      New_Line;
      Put (Head("Height", Column_1_Width));
      Put (Surface.Information.Height, Column_2_Width);
      New_Line;
      Put (Head("Plane_Count", Column_1_Width));
      Put (Surface.Information.Plane_Count, Column_2_Width);
      New_Line;
      Put (Head("Pixel_Size", Column_1_Width));
      Put (Surface.Information.Pixel_Size, Column_2_Width);
      New_Line;
      Put (Head("Compression", Column_1_Width));
      Put (Tail(Surface.Information.Compress'Img, Column_2_Width));
      New_Line;
      Put (Head("Image_Size", Column_1_Width));
      Put (Surface.Information.Image_Size, Column_2_Width);
      New_Line;
      Put (Head("Horizontal_Resolution", Column_1_Width));
      Put (Surface.Information.Horizontal_Resolution, Column_2_Width);
      New_Line;
      Put (Head("Vertical_Resolution", Column_1_Width));
      Put (Surface.Information.Vertical_Resolution, Column_2_Width);
      New_Line;
      Put (Head("Color_Count", Column_1_Width));
      Put (Surface.Information.Color_Count, Column_2_Width);
      New_Line;
      Put (Head("Important_Color_Count", Column_1_Width));
      Put (Surface.Information.Important_Color_Count, Column_2_Width);
      New_Line;
   end;




   procedure Put_Lines (Surface : BMP_Information_V5) is
      use Ada.Text_IO;
      use Ada.Integer_Text_IO;
      use Ada.Strings.Fixed;
      use Interfaces;
      package Unsigned_32_Text_IO is new Modular_IO (Unsigned_32);
      package Unsigned_16_Text_IO is new Modular_IO (Unsigned_16);
      use Unsigned_32_Text_IO;
      use Unsigned_16_Text_IO;
      Column_1_Width : constant := 25;
      Column_2_Width : constant := 20;

   begin
      Put (Head ("BMP_Information'Size / Storage_Unit", Column_1_Width));
      Put (Integer (BMP_Information'Size / Storage_Unit), Column_2_Width);
      New_Line;


      Put (Head ("Signature", Column_1_Width));
      Put (Tail (Surface.File.Sign'Img, Column_2_Width));
      New_Line;
      Put (Head("Size ", Column_1_Width));
      Put (Surface.File.Size, Column_2_Width);
      New_Line;
      Put (Head("Reserved_1", Column_1_Width));
      Put (Surface.File.Reserved_1, Column_2_Width);
      New_Line;
      Put (Head("Reserved_1", Column_1_Width));
      Put (Surface.File.Reserved_1, Column_2_Width);
      New_Line;
      Put (Head("Offset", Column_1_Width));
      Put (Surface.File.Offset, Column_2_Width);
      New_Line;
      Put (Head("Header_Size", Column_1_Width));
      Put (Surface.Information.Header_Size, Column_2_Width);
      New_Line;
      Put (Head("Width", Column_1_Width));
      Put (Surface.Information.Width, Column_2_Width);
      New_Line;
      Put (Head("Height", Column_1_Width));
      Put (Surface.Information.Height, Column_2_Width);
      New_Line;
      Put (Head("Plane_Count", Column_1_Width));
      Put (Surface.Information.Plane_Count, Column_2_Width);
      New_Line;
      Put (Head("Pixel_Size", Column_1_Width));
      Put (Surface.Information.Pixel_Size, Column_2_Width);
      New_Line;
      Put (Head("Compression", Column_1_Width));
      Put (Tail(Surface.Information.Compression'Img, Column_2_Width));
      New_Line;
      Put (Head("Image_Size", Column_1_Width));
      Put (Surface.Information.Image_Size, Column_2_Width);
      New_Line;
      Put (Head("Horizontal_Resolution", Column_1_Width));
      Put (Surface.Information.Horizontal_Resolution, Column_2_Width);
      New_Line;
      Put (Head("Vertical_Resolution", Column_1_Width));
      Put (Surface.Information.Vertical_Resolution, Column_2_Width);
      New_Line;
      Put (Head("Color_Count", Column_1_Width));
      Put (Surface.Information.Color_Count, Column_2_Width);
      New_Line;
      Put (Head("Important_Color_Count", Column_1_Width));
      Put (Surface.Information.Important_Color_Count, Column_2_Width);
      New_Line;
      Put (Head("Red_Channel_Bitmask", Column_1_Width));
      Put (Surface.Information.Red_Channel_Bitmask, Column_2_Width);
      New_Line;
      Put (Head("Green_Channel_Bitmask", Column_1_Width));
      Put (Surface.Information.Green_Channel_Bitmask, Column_2_Width);
      New_Line;
      Put (Head("Blue_Channel_Bitmask", Column_1_Width));
      Put (Surface.Information.Blue_Channel_Bitmask, Column_2_Width);
      New_Line;
      Put (Head("Alpha_Channel_Bitmask", Column_1_Width));
      Put (Surface.Information.Alpha_Channel_Bitmask, Column_2_Width);
      New_Line;
      Put (Head("Color_Space_Type", Column_1_Width));
      Put (Surface.Information.Color_Space_Type, Column_2_Width);
      New_Line;
      Put (Head("Red_X", Column_1_Width));
      Put (Surface.Information.Red_X, Column_2_Width);
      New_Line;
      Put (Head("Red_Y", Column_1_Width));
      Put (Surface.Information.Red_Y, Column_2_Width);
      New_Line;
      Put (Head("Red_Z", Column_1_Width));
      Put (Surface.Information.Red_Z, Column_2_Width);
      New_Line;
      Put (Head("Green_X", Column_1_Width));
      Put (Surface.Information.Green_X, Column_2_Width);
      New_Line;
      Put (Head("Green_Y", Column_1_Width));
      Put (Surface.Information.Green_Y, Column_2_Width);
      New_Line;
      Put (Head("Green_Z", Column_1_Width));
      Put (Surface.Information.Green_Z, Column_2_Width);
      New_Line;
      Put (Head("Blue_X", Column_1_Width));
      Put (Surface.Information.Blue_X, Column_2_Width);
      New_Line;
      Put (Head("Gamma_Red", Column_1_Width));
      Put (Surface.Information.Gamma_Red, Column_2_Width);
      New_Line;
      Put (Head("Gamma_Green", Column_1_Width));
      Put (Surface.Information.Gamma_Green, Column_2_Width);
      New_Line;
      Put (Head("Intent", Column_1_Width));
      Put (Surface.Information.Intent, Column_2_Width);
      New_Line;
      Put (Head("Profile_Data", Column_1_Width));
      Put (Surface.Information.Profile_Data, Column_2_Width);
      New_Line;
      Put (Head("Profile_Size", Column_1_Width));
      Put (Surface.Information.Profile_Size, Column_2_Width);
      New_Line;
      Put (Head("Reserved", Column_1_Width));
      Put (Surface.Information.Reserved, Column_2_Width);
      New_Line;
   end;

end;
